/* Generated By:JJTree: Do not edit this line. ASTidentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stupaq.vhdl93;

public
class ASTidentifier extends SimpleNode {
  public ASTidentifier(int id) {
    super(id);
  }

  public ASTidentifier(VHDL93Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VHDL93ParserVisitor visitor, Object data) throws java.lang.Exception {
    return visitor.visit(this, data);
  }

  /** Customizations for {@link VHDL93Parser} compatibility. */
  public String name;
}
/* JavaCC - OriginalChecksum=526900e2f6ecf0ebbd69482689a5d137 (do not edit this line) */
