/* Generated By:JJTree: Do not edit this line. ASTidentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stupaq.vhdl93;

public
class ASTidentifier extends SimpleNode {
  public ASTidentifier(int id) {
    super(id);
  }

  public ASTidentifier(VHDL93Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public <Result, Argument, Failure extends Exception> Result jjtAccept(VHDL93ParserVisitor<Result, Argument, Failure> visitor, Argument data) throws Failure
  {
    return visitor.visit(this, data);
  }

  /** Customizations for {@link VHDL93Parser} compatibility. */
  public String name;
}
/* JavaCC - OriginalChecksum=fe2af3cdf962e64602cab72c96f66de1 (do not edit this line) */
