/* Generated By:JJTree: Do not edit this line. ASTidentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package stupaq.vhdl93;

public
class ASTidentifier extends SimpleNode {
  public ASTidentifier(int id) {
    super(id);
  }

  public ASTidentifier(VHDL93Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VHDL93ParserVisitor visitor, Object data) throws Exception{
    return visitor.visit(this, data);
  }

  /** Customizations for {@link VHDL93Parser} compatibility. */
  public String name;
}
/* JavaCC - OriginalChecksum=859976eccf1fda894d32b00e9b9db89c (do not edit this line) */
